os:
- linux

language: php

before_install:
  - mkdir -p "$HOME/bin"
  - export PATH="$HOME/bin:$PATH"
  - if [ -n "$GITHUB_AUTH_TOKEN" ]; then echo "Github auth token found."; fi
  - if [ ! -d "$HOME/.phive" ]; then mkdir "$HOME/.phive"; fi
  - if [ ! -f "$HOME/.phive/phive.phar" ]; then ant getphive; mv phive.phar "$HOME/.phive/"; fi
  - install --mode=0755 -T "$HOME/.phive/phive.phar" "$HOME/bin/phive"

install:
  - ant setup

script: ./tools/phpunit

php:
  - 7.2
  - 7.3
  - 7.4
  - 7.2snapshot
  - 7.3snapshot
  - 7.4snapshot
  - master

matrix:
  allow_failures:
    - php: master
  fast_finish: true

notifications:
  email: false
